Docs/documento-planejamento/cronograma-executado.md, Docs/documento-planejamento/cronograma-planejado.md, mkdocs.yml
- Finalização da página "Cronograma planejado"
- Adição dá página "Cronograma executado"
Documentação - Página de Planejamento #15
=> [documentação] Finalização cronograma planejado e adição do cronograma executado

Docs/atas-reuniao/equipe/ata-reuniao-1.md, Docs/atas-reuniao/equipe/ata-reuniao-2.md, Docs/atas-reuniao/equipe/ata-reuniao-3.md, Docs/atas-reuniao/equipe/ata-reuniao-4.md, Docs/documento-planejamento/cronograma-planejado.md, Docs/documento-pre-rastreabilidade/aplicativo_selecionado.md, Docs/documento-pre-rastreabilidade/aplicativos_analisados.md, mkdocs.yml
- Padronização de tabelas, figuras e tabelas de versionamento
Entrega 1 - Validação Final do Projeto #16
=> [Documentação]: Padronização de elementos e correção de alguns componentes

Docs/documento-pre-rastreabilidade/aplicativo_selecionado.md
Este PR resolve os conflitos de mesclagem encontrados ao atualizar a branch doc/sprint4-aplicativo-selecionado com as últimas alterações da main. Após a resolução dos conflitos, o conteúdo da branch foi atualizado, mantendo as alterações feitas localmente e integrando-as com a versão mais recente da main.
**Alterações:**
- Ajuste de fontes e referências
- Resolução de conflitos no arquivo Docs/documento-pre-rastreabilidade/aplicativo_selecionado.md.
- Atualização da branch doc/sprint4-aplicativo-selecionado para refletir as últimas modificações da branch main.
=> Resolução de conflitos e atualização da branch doc/sprint4-aplicativo-selecionado

Docs/documento-planejamento/cronograma-executado.md, Docs/documento-planejamento/cronograma-planejado.md, Docs/documento-planejamento/ferramentas-utilizadas.md, Docs/documento-planejamento/metodologias-utilizadas.md, Docs/documento-pre-rastreabilidade/aplicativo_selecionado.md, mkdocs.yml
- Inserido arquivo PDFs na parte do aplicativo selecionado
- Criada nova branch `fix/atualizacoes-e-reformas-pendentes` para manter histórico limpo de contribuições, não apague a branch após aceitar o pr por favor.
- Padronização do caminho de arquivos estáticos seguindo as boas práticas da equipe.
Caso outro membro deseje atualizar esse conteúdo, os arquivos estão organizados perfeitamente
=> fix: correção em diversos subtópicos e ajustes em algumas partes da referência

Docs/documento-inspecao/grupo+1/documento_inspecao_grupo+1.md, Docs/documento-inspecao/grupo/documento_inspecao_grupo.md, Docs/documento-planejamento/cronograma-planejado.md, Docs/documento-verificacao/documento-verificacao-grupo.md
`fix: padronização de histórico de versões e bibliografias`
Este PR padroniza o histórico de versões e a estrutura de bibliografia em todos os menus e subtópicos do projeto.  
Além disso, foram feitas revisões nos tópicos existentes para garantir uniformidade e adequação às normas da disciplina.
- Atualização e padronização de bibliografias em todos os arquivos `.md`
- Padronização de tabelas de histórico de versões com autores, revisores e datas
- Adição de links nos autores para os perfis do GitHub
- Revisão de nomenclatura e padronização de data
[Arthur Carvalho](https://github.com/arthurlleite)
- @leozinlima
- @Bessazs
=> doc: ajustes no histórico de versões e no cronograma planejado

Docs/documento-planejamento/cronograma-executado.md, Docs/documento-planejamento/cronograma-planejado.md, Docs/documento-planejamento/ferramentas-utilizadas.md, Docs/documento-planejamento/metodologias-utilizadas.md, Docs/documento-pre-rastreabilidade/documento-pre-rastreabilidade.md, Docs/documento-verificacao/documento-verificacao-grupo.md
=> [doc] Padronização de alguns títulos do documento

Docs/documento-elicitacao/FirstThingFirst.md, Docs/documento-elicitacao/Personas.md, Docs/documento-elicitacao/QFD.md, Docs/documento-pre-rastreabilidade/aplicativo_selecionado.md
> Descrição 
Este *pull request* propõe melhorias e ajustes em diversos documentos da fase de elicitação e pré-rastreabilidade, com foco em clareza, formatação e padronização. As alterações incluem:
- `FirstThingFirst.md`  
- `Personas.md`  
- `QFD.md`  
- 'aplicativo_selecionado.md`
=> [doc] Atualização do documento de Personas

Docs/documento-elicitacao/100.md, Docs/documento-elicitacao/MoSCoW.md, Docs/documento-elicitacao/PerfilUsuario.md, Docs/documento-elicitacao/Questionario.md
Este Pull Request tem como objetivo realizar ajustes nas referências bibliográficas e cruzadas em diversos documentos da seção de elicitação. As alterações foram feitas para garantir maior consistência, correção e conformidade com o padrão de formatação adotado no projeto.
Arquivos Modificados
> Docs/documento-elicitacao/100.md
> 
> Docs/documento-elicitacao/MoSCoW.md
> 
> Docs/documento-elicitacao/PerfilUsuario.md
> 
> Docs/documento-elicitacao/Questionario.md
Mudanças Realizadas
=> [doc] Ajuste de referências

Docs/documento-elicitacao/Observacao.md, Docs/documento-elicitacao/Personas.md, Docs/documento-elicitacao/Storytelling.md
=> [docs] ajuste de arquivos

Docs/documento-elicitacao/Personas.md
=> [doc] Alteração

Docs/documento-modelagem/cenario.md
=> [documentação] Adicionar Cenários

Docs/documento-inspecao/grupo+1/documento_inspecao_grupo+1-2.md, Docs/documento-inspecao/grupo+1/documento_inspecao_grupo+1-3.md, Docs/documento-inspecao/grupo+1/documento_inspecao_grupo+1.md, Docs/documento-inspecao/grupo/documento_inspecao_grupo.md, Docs/documento-inspecao/grupo/documento_inspecao_grupo2.md, Docs/documento-inspecao/grupo/documento_inspecao_grupo3.md, Docs/documento-verificacao/documento-verificacao-grupo.md, Docs/documento-verificacao/documento-verificacao-grupo2.md, Docs/documento-verificacao/documento-verificacao-grupo3.md
- Casos de Uso
- Cenários
- Léxicos
- Especificação Suplementar
As análises foram baseadas em critérios definidos nas checklists da equipe e boas práticas de Engenharia de Requisitos.
---
- Os casos de uso apresentam nomes claros com verbos no infinitivo.
- O ator principal está corretamente posicionado fora da fronteira do sistema.
- Há uso apropriado de elipses, relacionamentos (`include`, `extend`) e fronteiras do sistema.
- Os fluxos principais estão descritos, porém alguns casos carecem de exceções e pós-condições detalhadas.
**✔ Recomendação:** Revisar os fluxos alternativos e exceções para melhor cobertura de comportamento.
---
- Todos os cenários apresentam título, objetivos, contexto, atores, recursos e episódios.
- Os episódios seguem ordem lógica e representam situações …
=> Verificação e Inspeção dos Artefatos – Entrega 3

Docs/documento-modelagem/Agil/Backlog.md, Docs/documento-modelagem/Agil/Historias_de_usuario.md, Docs/documento-modelagem/Agil/NR_Framework.md, Docs/documento-planejamento/cronograma-executado.md, Docs/documento-planejamento/cronograma-planejado.md, mkdocs.yml
- Adicionados os seguintes arquivos:
- `Backlog.md`: documento inicial do backlog do projeto
- `Historias_de_usuario.md`: início da documentação de histórias de usuário
- `NR_Framework.md`: descrição do framework ágil adotado
- Atualização do cronograma planejado (`cronograma-planejado.md`)
- Atualização do cronograma executado (`cronograma-executado.md`)
- Atualização do arquivo `mkdocs.yml` para inclusão dos novos documentos
=> doc: Criação da documentação inicial: Ágil

Docs/documento-modelagem/Agil/Historias_de_usuario.md
Este Pull Request adiciona as histórias de usuário **US07 a US12** ao arquivo `Historias_de_usuario.md`, localizado no diretório `Docs/documento-modelagem/Agil/`.  
Essas histórias estão relacionadas às funcionalidades de **registro de boletins de ocorrência** e **segurança do usuário** no aplicativo **Celular Seguro**.
=> doc: Adição de Histórias de usuário US07 a US12.

Docs/documento-modelagem/Agil/Historias_de_usuario.md
Este Pull Request realiza as seguintes alterações na documentação do projeto **Celular Seguro**:
---
Foram incluídas 7 histórias de usuário baseadas na elicitação e validação feita com a usuária Luiza. Cada história foi documentada seguindo o modelo acordado de apresentação em estilo colapsável (accordion), incluindo os seguintes campos:
- **ID**
- **Nome**
- **Descrição (formato: "Eu, como usuário, gostaria...")**
- **Critérios de Aceitação**
- **Rastreabilidade** com links clicáveis para os documentos de origem
- **Prioridade**
- **Fonte** com autoria direcionada para o GitHub do colaborador: [Arthur Carvalho](https://github.com/arthurlleite)
As histórias cobrem os seguintes requisitos:
| ID     | Requisito                                         | Prioridade | …
=> Doc: Us00 até a Us06 feita e página padronizada

Docs/documento-modelagem/Agil/Backlog.md
1. **Coleta das Histórias**: Reuniu todas as US do “Celular Seguro” (US00 a US36) no arquivo de histórias de usuário.
2. **Agrupamento**: Identificou temas (“Funcionalidades” e “Qualidade & Confiabilidade”) e, a partir deles, definiu cinco épicos principais que cobrem cadastro de dispositivos, boletim de ocorrência, conta & perfil, comunicação & notificações e pessoa de confiança.
3. **Decomposição em Features**: Para cada épico, listou as features intermediárias (ex.: “Leitura de IMEI”, “Registro de boletim”, “Redefinir senha” etc.) e vinculou as US correspondentes.
4. **Priorização e Estimativas**: Manteve a prioridade (Alta, Média, Baixa) que já estava definida em cada história e considerou estimativas de esforço em horas.
5. **Montagem da Tabela**: Criou uma tabela em Markdown/HTML …
=> docs: Criação do backlog

Docs/documento-modelagem/Agil/NR_Framework.md
Este Pull Request adiciona dois Cartões de Especificação do **NFR Framework** relacionados à funcionalidade **Registrar Telefone** no aplicativo **Celular Seguro**.
---
Foram documentados dois requisitos não funcionais priorizados com base nas heurísticas do QFD e validados com o usuário, abordando aspectos essenciais de **usabilidade** e **segurança** no registro de telefone.
| Tabela | Requisito | Tema Principal                     | Prioridade |
|--------|-----------|------------------------------------|------------|
| 7      | RNF01     | Usabilidade com affordances visuais | Alta (4.3) |
| 8      | RNF02     | Segurança criptográfica no registro | Alta (4.6) |
---
- Menus e botões devem ter estrutura clara, com ícones e feedbacks visuais para ações como adicionar e remover números.
- …
=> docs(nfr): adiciona cartões de especificação RNF01 e RNF02 para o menu "Registrar Telefone"

Docs/documento-modelagem/Agil/NR_Framework.md
Este Pull Request adiciona as tabelas  **nfr 11 e  nfr12** ao arquivo `NR_Framework.md`, localizado no diretório `Docs/documento-modelagem/Agil/`.
=> Doc/Adição das tabelas 11 e 12 e padronização das tabelas

README.md, mkdocs.yml
Remoção Icones no readme
Alocação da barra superior de menus para a lateral
=> ajuste no readme e menu superior

Docs/documento-planejamento/cronograma-executado.md, Docs/documento-planejamento/cronograma-planejado.md, Docs/documento-planejamento/documento-planejamento.md, Docs/documento-planejamento/ferramentas-utilizadas.md, Docs/documento-planejamento/heatmap.md, Docs/documento-planejamento/metodologias-utilizadas.md, Docs/documento-validacao/documentacao-artefatosAnteriores.md
- insercao dos modelo das tabelas de contribuicao e ajustes no layout de cada artefato
=> refactor: reorganizacao do artefato de planejamento

Docs/documento-elicitacao/AnalisedeDocumentos.md, Docs/documento-elicitacao/Brainstorming.md, Docs/documento-elicitacao/Observacao.md, Docs/documento-elicitacao/Questionario.md, Docs/documento-elicitacao/Storytelling.md, Docs/documento-elicitacao/requisitos_elicitados.md
tabelas de contribuição da elicitação de requisitos
- questionario
-  storytelling
-  observação
- brainstorming 
- analise de documentos
=> tabela de contribuicao das tecnicas de elicitacao

Docs/documento-entrega-final/sintetizacao-videos.md
Este pull request realiza ajustes de formatação e conteúdo na página da documentação `sintetizacao-videos.md` do projeto **Celular Seguro**, com foco em:
- Inclusão de breve descrição introdutória e da tabela gravação e participantes.
---
---
---
=> feature: criação da tabela de apresentação feita
